### ISSUE TITLE
PHPSP - Liberação de Acesso a publicação de artigos

### ISSUE THREAD

**Issue by leviferreira** [PHPSP/phpsp-blog#4]
Galera,

Como eu faço para publicar artigos ? O Usuário que eu cadastrei é leviferreira

[]'s

**Comment by rogeriopradoj** [comment]
@duodraco, pode me ajudar nessa?

**Comment by filhodanuvem** [comment]
Boa, meu usuário é @cloudson e também está "congelado"

**Comment by rogeriopradoj** [comment]
@leviferreira e @cloudson, foi enviada a senha inicial para troca no Gtalk/Hangout de vocês, no e-mail que vocês usaram para cadastro.

Entrem lá no site e troquem por uma senha nova, ok?

Estou fechando a issue, qualquer problema, abram uma nova, certo?

Até mais!

**Comment by filhodanuvem** [comment]
Valeu @rogeriopradoj !!! Consegui acessar! :+1:

**Comment by leviferreira** [comment]
@rogeriopradoj Não recebi nada no gtalk. Abs

**Comment by rogeriopradoj** [comment]
@leviferreira, verifique novamente.

Se não funcionar, coloca o seu gtalk aqui, ok?

Até

**Comment by leviferreira** [comment]
@rogeriopradoj Agora Rolou! Abs
