### ISSUE TITLE
Página de Membros > Twitter não funciona

### ISSUE THREAD

**Issue by williancarminato** [PHPSP/phpsp-blog#6]
http://phpsp.org.br/index.php/membros/twitters/

A página deveria listar o twitter das pessoas com a regra indicada, mas não está funcionando.

**Comment by williamespindola** [comment]
Página extinta agora http://phpsp.org.br/como-contribuir/
Issue pode ser fechada.

**Comment by hussani** [comment]
Fechando porque a página foi excluída.
