### ISSUE TITLE
Página: Ver Todos as Artigos

### ISSUE THREAD

**Issue by jackmakiyama** [PHPSP/phpsp-blog#9]
O link que a pagina inicial direciona está quebrado
http://phpsp.org.br/category/artigos/

E acho que o certo seria: Ver Todos os Artigos

**Comment by rogeriopradoj** [comment]
Olá, @jackmakiyama . O link quebrado tem a ver com a issue #7, que já está sendo tratada.

Não vou fechar essa como duplicada pois tem que acertar esse "as" por "os", certo?

@duodraco, sabe dizer se isso é no tema, ou é possível trocar via administração do wordpress?

Valeu

**Comment by jackmakiyama** [comment]
Ok, desculpe-me pele duplicação.

**Comment by rogeriopradoj** [comment]
Consertado, agora está como "Ver todos os artigos...".

Valeu @jackmakiyama.

@duodraco só avisar: já editei na produção também (não sei quando seria feito "deploy" desse aqui)
